# Generated by Django 3.2.7 on 2021-09-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInfo',
            fields=[
                ('tag_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('อยู่', 'อุปกรณ์อยู่'), ('ไม่อยู่', 'อุปกรณ์ไม่อยู่')], default='ไม่อยู่', max_length=20)),
                ('borrow_time', models.DateTimeField()),
                ('student_id', models.CharField(default='-', max_length=20)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
