# Generated by Django 3.2.7 on 2021-11-19 02:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='NotAllowed')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInfo',
            fields=[
                ('tag_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('อุปกรณ์อยู่', 'อุปกรณ์อยู่'), ('อุปกรณ์ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('ถูกยืม', 'ถูกยืม')], default='อยู่', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ObjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ObjectHistory')),
                ('borrow_time', models.DateTimeField()),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.objectinfo')),
            ],
        ),
        migrations.CreateModel(
            name='NotFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeout_time', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 2, 55, 20, 192889))),
                ('not_allow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.notallowed')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.objectinfo')),
            ],
        ),
    ]
