# Generated by Django 3.2.7 on 2021-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfo',
            name='borrow_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
