# Generated by Django 3.2.7 on 2021-11-30 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfound',
            name='takeout_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 23, 4, 57, 655013)),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='borrow_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='status',
            field=models.CharField(choices=[('อุปกรณ์อยู่', 'อุปกรณ์อยู่'), ('อุปกรณ์ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('ถูกยืม', 'ถูกยืม'), ('คืนของ', 'คืนของ')], default='อยู่', max_length=20),
        ),
    ]
