# Generated by Django 3.2.7 on 2021-11-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfound',
            name='takeout_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 2, 56, 35, 323123)),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ObjectInfo'),
        ),
    ]
