# Generated by Django 3.2.7 on 2021-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_alter_objectinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfo',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
