# Generated by Django 3.2.7 on 2021-12-09 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_alter_notfound_takeout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfound',
            name='takeout_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 15, 55, 133111)),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='status',
            field=models.CharField(choices=[('อุปกรณ์อยู่', 'อุปกรณ์อยู่'), ('อุปกรณ์ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('ถูกยืม', 'ถูกยืม'), ('คืนของ', 'คืนของ')], default='อุปกรณ์อยู่', max_length=20),
        ),
    ]
