# Generated by Django 3.2.7 on 2021-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0005_alter_objectinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfo',
            name='status',
            field=models.CharField(choices=[('อยู่', 'อุปกรณ์อยู่'), ('ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('ดำเนินการ', 'ดำเนินการ')], default='อยู่', max_length=20),
        ),
    ]
