# Generated by Django 3.2.7 on 2021-10-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0006_alter_objectinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectinfo',
            name='borrow_time',
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='status',
            field=models.CharField(choices=[('อยู่', 'อุปกรณ์อยู่'), ('ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('ดำเนินการ', 'กำลังดำเนินการ')], default='อยู่', max_length=20),
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('borrow_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.objectinfo')),
            ],
        ),
    ]
