# Generated by Django 3.2.7 on 2021-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0007_auto_20211026_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthistory',
            name='return_time',
            field=models.DateTimeField(blank=True, default='-', null=True),
        ),
    ]
