# Generated by Django 3.2.7 on 2021-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0009_alter_objecthistory_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfo',
            name='status',
            field=models.CharField(choices=[('อยู่', 'อุปกรณ์อยู่'), ('ไม่อยู่', 'อุปกรณ์ไม่อยู่'), ('ดำเนินการ', 'กำลังดำเนินการ'), ('ถูกยืม', 'ถูกยืม')], default='อยู่', max_length=20),
        ),
    ]
